spring:
  application:
    name: dataproject
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DATABASE_URL:}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 180000
      idle-timeout: 60000
      connection-timeout: 30000
      keepalive-time: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 5000
        order_inserts: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

app:
  storage:
    path: "${STORAGE_PATH:C:\\var\\log\\applications\\API\\dataprocessing\\}"
